---
title: "13probabiliy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 추론통계학
* 어떤 일에 대해 미래에 발생할 가능성을 계산

# 확률
* 오랜시간동안 경험적으로 쌓아온 확률현상에 대한 경험적 인식을 바탕으로 이론화한 것
* 어떤 일이 발생할 가능성이나 믿음의 정도를 나타낸 것
* 0과 1사이의 숫자를 그 사건  A가 일어날 확률
* 어떤 일이 일어날 경우의 수 / 모든 일이 일어날 경우의 수
* 1-일어날 확률 = 일어나지 않을 확률

# 표본공간

# 사건


# 확률의 합사건/곱사건

# 조건부 확률

# 전체확률의 법칙

# 베이즈의 정리


# 확률변수

# 확률분포

```{r}
# 주사위 2개를 던졌을 때 나올 수 있는 모든 눈금의 합에 대한 확률
x <- seq(2:12)
y <- c(1/36, 2/36, 3/36, 4/36, 5/36, 6/36, 5/36, 4/36, 3/36, 2/36, 1/36)
plot(x, y, col='red', type='b')

```
# 표준정규분포
# 중심극한의 정리
  * 


# R의 확률분포 함수명
* 확률분포 함수명은 기능접두사 + 확률분포명으로 표기
* 정규분포 : norm/dnorm/pnorm/qnorm/rnorm
    * d : 확률밀도함수
    * p : 누적 분포 함수
    * q : 분위수 계산
    * r : 무작위 난수(샘플) 생성
    
```{r}
# -4~4사이 0.1 간격으로 정규분포 그래프를 그리세요
# dnorm(대상, 평균, 표준편차
x <- seq(-4, 4, 0.1)
y <- dnorm(x, 0, 1)
plot(x, y, type='l', col='blue')
```
```{r}
# 서로 다른 공장의 근로자 근속연수를 정규분포로 표현
# 근속년수가 5~35사이고, 평균년수가 20일 때
# 각 공장별 표준편차의 변화(3.1, 3.9, 5)에 따른 정규분포그래프
x <- seq(5, 35)
plot(dnorm(x, mean=20, sd=3.1), type='l', col='red')
lines(dnorm(x, mean=20, sd=3.9), type='l', col='blue')
lines(dnorm(x, mean=20, sd=5), type='l', col='yellow')
# 표준편차가 커질수록 그래프는 완만해 짐
```
```{r}
#어떤 상품 3개의 무개를 정규분포로 나타냄 (범위 : 270~330)
# 각 상품의 무게가 283/301/321 그램으로 다르고 표준편차는 1.6으로 동일할 때 정규분포 그래프로 나타낸다면?
x <- seq(270, 330)
plot(dnorm(x, mean=283, sd=1.6), type='l', col='red')
lines(dnorm(x, mean=301, sd=1.6), type='l', col='blue')
lines(dnorm(x, mean=321, sd=1.6), type='l', col='purple')
# 평균이 달라지면 그래프가 이동함
```
# 정규화와 z값이 필요한 이유

```{r}
# 평균이 0이고 표준편차가 1인 정규분포에서 
# z값이 1.15이하/2.14이상/-2.17~1.79일 확률은?
x <- seq(-3, 3, 0.1)
plot(dnorm(x, mean=0, sd=1), col='red', type='l')
```
```{r}
# Z값이 1.15이하(왼쪽 꼬리)
# 즉, q값을 기준으로 -inf ~ q의 누적값을 계산
pnorm(q=1.15, mean=0, sd=1, lower.tail=T)

# z값이 2.17이상 (오른쪽 꼬리)
# 즉, q값을 기준으로 q ~ +inf의 누적값을 계산
pnorm(q=2.17, mean=0, sd=1, lower.tail=F)

# z값이 -2.17~1.79사이 
pnorm(q=1.79, mean=0, sd=1, lower.tail=F) - 
  pnorm(q=-2.17, mean=0, sd=1, lower.tail=F)

```

```{r}
# 성인남자 키는 평균 173cm, 표준편차 5인 정규분포를 따른다고 할 때, 
# 185cm 이상인 사람의 비율을 구하기 위한 z값은 얼마인가?
# 표준화값 = (표본-평균)/표준편차

# 185cm의 z값은? 
(185-173) / 5
# 따라서 평균 173cm, 표준편차 5인 정규분포를 
# 평균 0, 표준편차 1인 정규분포로 바꾸면 185cm는 2.4가 됨 
# => 표준정규분포표를 참고
# => 세로축 2.4, 가로축 0 => 0.0082

pnorm(q=185, 173, 5, lower.tail=F)
```
```{r}
# 우버택시 기사 수입이 평균 1000달러, 표준편차 100달러인 정규분포일 때,
# 주당 수입이 1100달러에 해당하는 z값은?
# 주당수입이 900달러에 해당하는 z값은?
# 주당수입이 900달러 이하일 확률은?
# 주당수입이 840~1200달러일 확률은?
(1100-1000)/100
(900-1000)/100
pnorm(900, 1000, 100, lower.tail = T)
(840-1000)/100 # -1.6  : 0.4452
(1200-1000)/100 # 2 : 0.0.4772
pnorm(1200,1000,100, lower.tail = T) -
  pnorm(840, 1000, 100, lower.tail = T)
```
```{r}
# 주당수입이 900달러 이하일 확률을 그래프로 시각화
# 정규화하기 전
a <- 700:1300
b <- dnorm(a, 1000, 100)
plot(a, b, type='l', col='red')

c <- 700:900
d <- dnorm(c, 1000, 100)
polygon(c(700, c, 900), c(0, d, 0), col='pink')

# 정규화한 후
x1 <- (700-1000)/100
x2 <- (1300-1000)/100
e <- seq(x1, x2, by=0.01)
f <- dnorm(e, 0, 1)
plot(e, f, type='l', col='blue')

x3 <- (900-1000)/100
g <- seq(x1, x3, 0.01)
h <- dnorm(g, 0, 1)
polygon(c(x1, g, x3), c(0, h, 0), col='navy')
```

```{r}
# 어떤 전구회사에서 생산하는 전구의 수명이 평균 800일,
# 표준편차는 40일인 정규분포를 따를 때, 전구의 수명이 750일 확률은?
# 또는 전구의 수명이 750 이상일 확률은?
dnorm(750, 800, 40) # 특정지점의 확률을 구할 때
pnorm(750, 800, 40, lower.tail=F)

```

```{r}

```

